############################################################################### 
# Authors:  Kathrine Aguirre
# Date:     Abril 2021
# Licence:  Apache v02
# Project:  Mongo Sharding
# Brief:    Docker compose file to configure whole application
#
# How to use the containers
#   - docker-compose -f docker-compose.yaml up -d
#
###############################################################################
version: '3'
services:
#------------------------------------------------------
# NODO 02
#------------------------------------------------------
  nodo-shard02-srv01:
    container_name: nodo-shard02-srv01
    image: mongo
    command: mongod --shardsvr --replSet nodo02-rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - ../data/nodo-shard02-srv01:/data/db
      - ../scripts:/scripts

  nodo-shard02-srv02:
    container_name: nodo-shard02-srv02
    image: mongo
    command: mongod --shardsvr --replSet nodo02-rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - ../data/nodo-shard02-srv02:/data/db
      - ../scripts:/scripts

  nodo-shard02-srv3:
    container_name: nodo-shard02-srv03
    image: mongo
    command: mongod --shardsvr --replSet nodo02-rs --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - ../data/nodo-shard02-srv03:/data/db
      - ../scripts:/scripts

