############################################################################### 
# Authors:  Kathrine Aguirre
# Date:     Abril 2021
# Licence:  Apache v02
# Project:  Mongo Sharding
# Brief:    Docker compose file to configure whole application
#
# How to use the containers
#   - docker-compose -f docker-compose.yaml up -d
#
###############################################################################
version: '3'
services:
#------------------------------------------------------
# Config Server
#------------------------------------------------------
  mongos-service:    
    hostname: mongos-service
    container_name: mongos-service 
    image: mongo
    command: mongos --configdb config-rs/10.0.0.10:40001,10.0.0.10:40002,10.0.0.10:40003 --bind_ip_all --port 27017
    restart: always
    ports:
      - 60000:27017
    volumes:    
      - ../scripts:/scripts  

