############################################################################### 
# Authors:  Kathrine Aguirre
# Date:     Abril 2021
# Licence:  Apache v02
# Project:  Mongo Sharding
# Brief:    Docker compose file to configure whole application
#
# How to use the containers
#   - docker-compose -f docker-compose.yaml up -d
#
###############################################################################
version: '3'
services:
#------------------------------------------------------
# Config Server
#------------------------------------------------------
  config-srv01:
    container_name: config-srv01
    image: mongo
    command: mongod --configsvr --replSet config-rs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:      
      - ./scripts:/scripts
      - ./data/nodo-config-srv01:/data/db

  config-srv02:
    container_name: config-srv02
    image: mongo
    command: mongod --configsvr --replSet config-rs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - ./scripts:/scripts
      - ./data/nodo-config-srv02:/data/db

  config-srv03:
    container_name: config-srv03
    image: mongo
    command: mongod --configsvr --replSet config-rs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - ./scripts:/scripts
      - ./data/nodo-config-srv03:/data/db
      

